config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :admin do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_admin_registration" # custom path to sign_up/registration
  end
  
  devise_for :admins, :skip => [:registrations]
	  
  resources :posts
  root to: "static_pages#home"
  #root to: "posts#index"
  get 'static_pages/contacts'
  get 'static_pages/projects'
  get 'static_pages/shop'
  get 'static_pages/draw_tree_submit'
  get 'static_pages/manage_over_hit'
  post 'static_pages/draw_tree_render'
  get 'static_pages/draw_tree_render' => 'static_pages/draw_tree_submit'
  # routes for elders 
  get 'static_pages/vincenzo_tomassi'
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/controllers/static_pages_controller.rb
require "csv"

class StaticPagesController < ApplicationController
before_action :authenticate_admin!, only: [:draw_tree_submit, :draw_tree_render, :manage_over_hit]

  def home

	@posts = Post.all.sort_by { |str| -str.views }
	print(@posts)
	print("TEST #1 => "+@posts[0].to_s+"\n")
		print("TEST #2 => "+@posts[0].title+"\n")
			print("TEST #1 => "+@posts[0].body.to_s+"\n")
			
	print(@posts[0].body.to_s)
  
  end

  def shop
  
  end
  
  def contacts
  end
  
  def projects
  
	    @posts = Post.all
		@families = Array.new
		@posts.each do |post_s|
		
			#print(post_s.family_name.to_s+"\n")
			if (post_s.family==true)
				if not @families.include?(post_s.family_name.to_s)
					@families.push(post_s.family_name.to_s)
				end
			end
			
		end
		
		print(@families)
		#####################################################
		@couples = Hash.new
		@families = @families.sort
		
		@families.each do |family_soprannome|
			buff_post = Array.new
				@posts.each do |post|
					if (family_soprannome==post.family_name.to_s and post.family==true)
						buff_post.push(post)
					end
				end
			
			#sorting by id per mantenere omogeneo l'ordine degli elementi nel menu ad eccezione dell'albero che compare in top.
			buff_post = buff_post.sort_by{|obj| obj.id}
			
			#gestione albero come primo elemento del dropdown menu
			family_tree = buff_post.find {|e| e.title == "Albero Genealogico"}
			print("TEST FAMILY TREEE ===> "+family_tree.to_s)
			buff_post.delete(family_tree)
			
			print("################buffpost###################")
			print(buff_post)
			if not(family_tree==nil)
				#unshift porta in prima posizione l'elemente family tree ovvero il post dal titolo Albero Genealogico se esiste
				buff_post.unshift(family_tree)
			end
			print("################buffpost###################")

		@couples[family_soprannome] = buff_post
		print(@couples)
		
		end
		
  end
  
  def draw_tree_submit
  
	@fullname = params[:fullname]	
	
  end
  
  def draw_tree_render
  
  print("TEST FULLNAME "+params[:fullname].to_s)
    print("TEST GENERATION LENGTH "+params[:generation_length].to_s)
	  print("TEST INDI_ID "+params[:whatever].to_s)



		def printTree(name,name_id,table,depth,generation,family_tree_structure)
			if name=="" or name==nil or generation==0 
				return
			else
			
				found = table.find {|row| row['FullName'] == name and row['INDI_ID'] == name_id} #=> returns first `row` that satisfies the block.

				father = (found.field("Father"))
				father_ID = (found.field("Father_ID"))
				mother = (found.field("Mother"))
				mother_ID = (found.field("Mother_ID"))
				
				
				#per evitare duplicati
				name = name+" "+name_id
					
				if(father_ID==nil)
				father_ID=" "
				end
				if(mother_ID==nil)
				mother_ID=" "
				end
				if(father==nil)
				father_ID="N.P."
				end
				if(mother==nil)
				mother_ID="N.P."
				end
				
				#calcolo date n/m per tooltip
				
				found_F = table.find {|row| row['FullName'] == father and row['INDI_ID'] == father_ID} 
				found_M = table.find {|row| row['FullName'] == mother and row['INDI_ID'] == mother_ID} 
				if(found_F == nil or found_M == nil)
				birth_F = "";
				death_F = "";
				birth_M = "";
				death_M = "";
				else
				birth_F = found_F.field("Birth");
				death_F = found_F.field("Death");
				birth_M = found_M.field("Birth");
				death_M = found_M.field("Death");
				end
				array_son_father = [father.to_s+" "+father_ID,name,birth_F.to_s+" "+death_F.to_s]
				array_son_mother = [mother.to_s+" "+mother_ID,name,birth_M.to_s+" "+death_M.to_s]
				family_tree_structure.push(array_son_father)
				family_tree_structure.push(array_son_mother)

				
						for i in 0..depth
						print("-")
						end
						
					print(found.field("FullName")+"\n")	
					printTree(father,father_ID,table,depth+1,generation-1,family_tree_structure)
					#depth=depth-1
					printTree(mother,mother_ID,table,depth+1,generation-1,family_tree_structure)
				
			end
		end 
		
	
	if (params[:fullname]==nil and params[:generation_length]==nil and params[:whatever]==nil)
		redirect_to controller: 'static_pages', action: 'draw_tree_submit'

	else
		print(params[:fullname])
		print(params[:generation_length])
		

	  
		table = CSV.parse(File.read("8566i1_9504225660cv5po3s1d11u_A.csv"), headers: true)
		
			#manage more than one hit
			
				found = table.select {|row| row['FullName'] == params[:fullname]}
				if found.length>1
				print("PIU' RISULTATI")
					for item in found
					  print(item.field('FullName').to_s+"  "+item.field('INDI_ID').to_s)
					  #print("\n")
					end
					
					if(params[:whatever]==nil)
						redirect_to controller: 'static_pages', action: 'manage_over_hit', generation_length: params[:generation_length], something: 'else', array_omonymous: found
					else
						family_tree_structure = Array.new
						print(params[:whatever])
						name_id = params[:whatever]
						name = table.find {|row| row['INDI_ID'] == name_id}.field("FullName")

						printTree(name,name_id,table,0,params[:generation_length].to_i,family_tree_structure)
						for item in family_tree_structure
						  print("test items in fts ==> "+item.to_s)
						end
						
						@final_family_tree = family_tree_structure
						#logger.debug "#{family_tree_structure}"
						
						gon.your_array = @final_family_tree
					end
					
				#end
				else
				print("UN SOLO RISULTATO")
					found = table.find {|row| row['FullName'] == params[:fullname]} #=> returns first `row` that satisfies the block.

					if (found==nil)
						flash[:notice] = 'Il nome da te digitato non è presente nel nostro database riprova'
						redirect_to static_pages_draw_tree_submit_path
					else

						family_tree_structure = Array.new

						name=found.field('FullName')
						name_id = table.find {|row| row['FullName'] == name}.field("INDI_ID")

						printTree(name,name_id,table,0,params[:generation_length].to_i,family_tree_structure)
						for item in family_tree_structure
						  print(item)
						end
						
						@final_family_tree = family_tree_structure
						#logger.debug "#{family_tree_structure}"
						
						gon.your_array = @final_family_tree
					end
		end		
		
		end
  
  end

  def manage_over_hit
  
	print(params[:id].to_s+"\n")
	print(params[:something].to_s+"\n")
	#print(params[:array_omonymous])
	print("TEST PRINT GEN LENGTH ====> "+params[:generation_length].to_s)
	collection_omonymous = params[:array_omonymous]
	arr_fullname = collection_omonymous[0].split(",")
	@fullname = arr_fullname[1]
	@result_array = Array.new
	@generation_length = params[:generation_length]
	
	for people in collection_omonymous
		info_array = people.split(',')
		buff_array = Array.new
		string_opt = "nato il: " +info_array[9]+ " a: "+info_array[10]+" || padre: "+info_array[19] + " madre: "+ info_array[21]
		buff_array = [string_opt,info_array[0]]  	
		@result_array.push(buff_array)
	end
  
  
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_menu.html.erb
   <aside class="col-sm-3 flex-grow-sm-1 flex-shrink-1 flex-grow-0 pb-sm-0 pb-3">
            <div class="bg-light border rounded-3 p-1 h-100">
                <ul class="nav flex-sm-column flex-row mb-auto justify-content-center" aria-expanded="false">
					
					
					
					<% @posts.each do |post| %>	
					<li>
						<% if (post.family==false) %> 	
										<button type="button" class="btn bg-transparent">
										<li><%= link_to "#{post.title.to_s}", post_path(:id => post.id.to_i) %></li>
										</button>	
						<% end %>
					</li>
					<% end %>
					
					
					
					<!-- <li>
					  <button type="button" class="btn bg-transparent dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
						Chiss Mirena
					  </button>
					  <ul class="dropdown-menu">
						<li><a class="dropdown-item">Albero Genealogico</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item"><%= link_to "QR Vincenzo Tomassi", static_pages_vincenzo_tomassi_path %></a></li>
					  </ul>
					  </br>
					</li> -->
					
					<li>
						<% @couples.each do |family_soprannome, post_array| %>
							<button type="button" class="btn bg-transparent dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
								<%= family_soprannome %>
							</button>
						
								<ul class="dropdown-menu">
							
								<% post_array.each do |post| %>
									
									
										<li><a class="dropdown-item"><%= link_to "#{post.title.to_s}", post_path(:id => post.id.to_i) %></a></li>
									
									 
								<% end %>
								</ul>
								</br>
						<% end %>
					 
					</li>
					
                </ul>
            </div>
        </aside>

app/views/static_pages/contacts.html.erb
          <div class="text-white">
            <h1 class="mb-3">Manuel Tomassi </br> emperon.mt@gmail.com</h1>
			<h1 class="mb-3">Flavio Forlini </br> lordparseval@gmail.com</h1>
            <h1 class="mb-3">Valeria Ferone </br> valeriaferone@libero.it</h1>
            <h1 class="mb-3">Martina Gerardi </br> martinajanis94@gmail.com</h1>      
          </div>

app/views/static_pages/draw_tree_render.html.erb
<%= javascript_pack_tag 'draw_tree', 'data-turbolinks-track': 'reload' %>
<div id="chart_div"></div>
		 

app/views/static_pages/draw_tree_submit.html.erb
	 
		 <div class="text-white text-center">
           <h1> Calcola albero genealogico  </h1>
<h5> Inserisci il nome e il cognome nel formato Nome Cognome (iniziali in maiuscolo) per iniziare la ricerca. Ad esempio Flavio Forlini.  </h5>		   
         </div>
	
<p id="notice"><%= notice %></p>
<div class="justify-items-center">
<%= form_tag(static_pages_draw_tree_render_path, :method => :post) do%>
  <div class="field">
    <%= label_tag "Inserisci qui il nome completo del soggetto della ricerca" %><br>
    <%= text_field_tag :fullname, class: "form-control" %> </br>
	<%= label_tag "Indica il numero massimo di generazioni da esplorare" %><br>
	<%= number_field_tag :generation_length, @current_value, min: 1, max: 7, :step => 'any', class: "number", placeholder: @hint_value %>
  </div>
  <div class="actions">
    <%= submit_tag "Submit", class: "btn btn-primary"  %>
  </div>
<%end%>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
    <% if user_signed_in? %>
	
	<header>
          <div class="text-white">
            <h1 class="mb-3">Chiss D&rsquo;Aquin</h1>
            <h5 class="mb-4">Thx for signed up, major features are coming soon</h5> 
          </div>
  </header>
	
	<% else %>

	

 
	
	
	
	
	
<div id="intro" class="bg-image shadow-2-strong">
    <div class="text-white">
		<div class="row">
			<div class="col-sm-3"></div>
			<div class="col-sm-6 text-center border-dark border-bottom" >
  
				<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<div class="row"  >
								<div class="col-sm-3"></div>
								<div class="col-sm-6">
								<%= image_tag "chissdaquin.png", style: 'height:300px;width:300px;margin-bottom:10px;' %>
								</div>
								<div class="col-sm-3"></div>
							</div>
							<div class="row">
								<div class="carousel-caption "></div>
									<div class="larger">BENVENUTI</div>
									<p>Siamo un gruppo di ragazzi che si occupa di storia e genealogia della città di Aquino.</br> 
									Con le nostre ricerche abbiamo ricollegato molteplici famiglie e crediamo che </br>
									La chiave per valorizzare il nostro futuro è quella di comprendere il passato.</p>
								</div>
							</div>
						<div class="carousel-item">
							<div class="row">
								<div class="col-sm-3"></div>
								<div class="col-sm-6">
									<%= image_tag "aquino_ml.jpg", style: 'height:300px;width:300px;margin-bottom:10px;margin-top:20px;' %>
								</div>
								<div class="col-sm-3"></div>
							</div>
							<div class="row">
								<div class="carousel-caption d-none d-md-block">
							</div>
        <div class="larger">Anche sui Social</div>
        <p>Seguiteci anche sui social </br> 
		   vi aspettiamo sulla nostra pagina </br> 
		   <a href="https://m.facebook.com/chissdaquin/"><i class="fab fa-facebook fa-3x"></i></a> </br>
		   <a class="nav-link" href="https://www.instagram.com/chissdaquin/"><i id="insta" class="fab fa-instagram fa-3x"></i></a></p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="row"  >
								<div class="col-sm-3"></div>
								<div class="col-sm-6">
								<%= image_tag "pennacalamaio.jpg", style: 'height:200px;width:200px;margin-top:30px;margin-bottom:30px;' %>
								</div>
								<div class="col-sm-3"></div>
							</div>
							<div class="row">
								<div  id="body_post_preview" class="carousel-caption"></div>
									<div class="larger"><%= @posts[0].title %></br><hr>
									il: <%= @posts[0].created_at%></br><hr></div>
									<%= @posts[0].body %>
								</div>
							</div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
  
			</div>
			<div class="col-sm-3"></div>
		</div>
	</div>
</div>
							 

							 
            
	

 


  <% end %>

app/views/static_pages/home.js.erb
window.alert(5 + 6);
$(document).ready(function(){
    $('.carousel').carousel({
      interval: 2000
    })
  });  

app/views/static_pages/manage_over_hit.erb
MANAGE OVER HIT </br>
<%= form_tag(static_pages_draw_tree_render_path, :method => :post) do %>
<div class="field">
    <%= label_tag "Seleziona l'antenato corretto" %><br>
    <%= select_tag "whatever",options_for_select(@result_array) %> </br>
	 <%= hidden_field_tag 'generation_length', @generation_length  %>
	 <%= hidden_field_tag 'fullname', @fullname  %>
  </div>
  <div class="actions">
    <%= submit_tag "Submit", class: "btn btn-primary"  %>
  </div>
<%end%>
	

app/views/static_pages/projects.html.erb
<%= stylesheet_pack_tag 'projects', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'hello', 'data-turbolinks-track': 'reload' %>

<header class="py-3 mb-4 border-bottom shadow">
    <div class="container-fluid align-items-center d-flex ">
       
    </div>
</header>

<div class="container-fluid pb-3 flex-grow-1 d-flex flex-column flex-sm-row overflow-auto">
    <div class="row flex-grow-sm-1 flex-grow-0">
     
	 <%=render 'menu' %> 
	 
        <main class="col overflow-auto h-100">
            <div class="bg-light border rounded-3 p-3">
                <h2>Benvenuto</h2>
                <p>Questo è il cuore del nostro sito. Qui potrai trovare i nostri lavori, e i servizi che a mano mano andremo ad integrare.</p><hr />
				<p>Puoi aiutarti con il menu laterale ed il menù a tendina qui in alto. Clicca sul dossier desiderato ed inizia a leggere. Scoprirai che non si smette mai di imparare e che il passato è tanto attuale quanto il presente</p><hr />
				<p>Per eventuali problemi con il sito, o con le informazioni riportate, per qualsiasi cosa non esitate a contattarci nella sezione apposita dove troverete i nostri recapiti mail</p><hr />
								<%= image_tag "chissdaquin.png", style: 'height:220px;width:250px;' %>
                <h4>Grazie</h4>
                <p>Lo staff di Chiss D'Aquin</p><hr />
			</div>
        </main>
    </div>
</div>

app/views/static_pages/shop.html.erb
         <div class="text-white">
           <h1> COMING SOON  </h1></br>
pagina in allestimento per maggiori informazioni su collaborazioni genealogiche e merchandise consultare la pagina facebook di <a id="linkface" href="https://m.facebook.com/chissdaquin/" >Chiss D&rsquo;Aquin</a> 			
          </div>

app/views/static_pages/vincenzo_tomassi.html.erb
<%= stylesheet_pack_tag 'projects', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'hello', 'data-turbolinks-track': 'reload' %>

<header class="py-3 mb-4 border-bottom shadow">
    <div class="container-fluid align-items-center d-flex ">
        <div class="flex-grow-1 d-flex align-items-center">
            <div class="flex-shrink-0 dropdown">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://i.ibb.co/MkPBTnd/Whats-App-Image-2021-08-05-at-11-17-04.jpg" alt="user" width="50" height="50">
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
		  <li><a class="dropdown-item"><%= link_to "Torna ai progetti", static_pages_projects_path %></a></li>
          <li><a class="dropdown-item" href="#">QR Bunker</a></li>
          <li class="dropdown-submenu">
            <a class="dropdown-item dropdown-toggle" href="#">Chiss Mirena</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Albero Genealogico</a></li>
			  <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item"><%= link_to "QR Vincenzo Tomassi", static_pages_vincenzo_tomassi_path %></a></li>


              <li class="dropdown-submenu">
                <a class="dropdown-item dropdown-toggle" href="#">Subsubmenu</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Subsubmenu action</a></li>
                  <li><a class="dropdown-item" href="#">Another subsubmenu action</a></li>
                </ul>
              </li>
              <li class="dropdown-submenu">
                <a class="dropdown-item dropdown-toggle" href="#">Second subsubmenu</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Subsubmenu action</a></li>
                  <li><a class="dropdown-item" href="#">Another subsubmenu action</a></li>
                </ul>
              </li>



            </ul>
          </li>
        </ul>
            </div>
    </div>
</header>
<div class="container-fluid pb-3 flex-grow-1 d-flex flex-column flex-sm-row overflow-auto">
    <div class="row flex-grow-sm-1 flex-grow-0">
        <aside class="col-sm-3 flex-grow-sm-1 flex-shrink-1 flex-grow-0 pb-sm-0 pb-3">
            <div class="bg-light border rounded-3 p-1 h-100">
                <ul class="nav flex-sm-column flex-row mb-auto justify-content-between text-truncate">
                    <li class="nav-item">
                        <a href="#" class="nav-link px-2 text-truncate">
                            <span class="d-none d-sm-inline">QR Bunker</span>
                        </a>
                    </li>				 
					<li>
					  <button type="button" class="btn bg-transparent dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
						Chiss Mirena
					  </button>
					  <ul class="dropdown-menu">
						<li><a class="dropdown-item">Albero Genealogico</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item"><%= link_to "QR Vincenzo Tomassi", static_pages_vincenzo_tomassi_path %></a></li>
						
					  </ul>
					</li>
                </ul>
            </div>
        </aside>
        <main class="col overflow-auto h-100">
            <div class="bg-light border rounded-3 p-3">
                <h2>Vincenzo Tomassi</h2>
                <p> 
					NASCE AD AQUINO IL 6 GENNAIO 1883, IN VIA PESCIOLE, SECONDO DI 5 FIGLI MASCHI:
					ANGELO 1879, LIBERO 1885 (MORTO NEL 1887), LIBERANTONIO 1887, ERMINIO 1890.
					IL 16 LUGLIO 1903 SI SPOSA AD AQUINO CON GAETANA MARIA CONCETTA LUPO (1882-1960).
					IL 10 APRILE 1904 NASCE LA SUA PRIMA FIGLIA ANGELA.
					IL 12 OTTOBRE 1905 NASCE IL SUO PRIMO FIGLIO GIUSEPPE.
					NEL 1905 I FRATELLI EMIGRANO IN AMERICA.
					IL 2 DICEMBRE 1908 NASCE LA SUA SECONDA FIGLIA NICOLINA.
					NEL 1909 EMIGRA CON LA NAVE DI NOME BERLIN NEL PORTO DI CASERTA DESTINAZIONE UTICA,NY 
					FA SUCCESSIVAMENTE RITORNO.
				</p>
				</hr>
				
				<p><%= image_tag "vincenzo_tomassi_1883.jpg", loading: "lazy", alt: "…", width: "200", height: "200" %></p> </hr>

				
				
				<p> 
					L'8 MAGGIO 1911 NASCE LA SUA TERZA FIGLIA CELESTE.
					NEL'INTORNO DEL  1912 IL FRATELLO MAGGIORE ANGELO MUORE IN AMERICA LASCIANDO UN FIGLIO PICCOLO ALLE CURE DI SUO FRATELLO
					E SUA COGNATA (SUA MOGLIE MORIRA' NEL 1918 PER MALATTIA), GAETANO.
					IL 16 DICEMBRE 1912 NASCE LA SUA QUARTA FIGLIA GELTRUDE.
					IL 25 LUGLIO 1914 NASCE LA SUA QUINTA FIGLIA FRANCESCA.
					L'11 NOVEMBRE DEL 1916 NASCE IL SUO SECONDO FIGLIO MASCHIO, OMONIMO, VINCENZO.
					IL 20 MAGGIO 1919 NASCE IL SUO TERZO FIGLIO MASCHIO ALESSANDRO.
					IL 2 SETTEMBRE 1921 NASCE IL SUO QUARTO FIGLIO MASCHIO ROCCO.
					IL 18 SETTEMBRE 1924 NASCE IL SUO QUINTO, E ULTIMO FIGLIO, SAVERIO.
				</p>
                <hr />
				<p><%= image_tag "foto_famiglia.jpg", loading: "lazy", alt: "…", width: "600", height: "350" %></p> </hr>
				<p><%= image_tag "foto_famiglia_2.jpg", loading: "lazy", alt: "…", width: "400", height: "350" %></p> </hr>
                </div>
        </main>
    </div>
</div>