config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :admin do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_admin_registration" # custom path to sign_up/registration
  end
  
  devise_for :admins, :skip => [:registrations]
	  
  resources :posts
  root to: "static_pages#home"
  #root to: "posts#index"
  get 'static_pages/contacts'
  get 'static_pages/projects'
  get 'static_pages/shop'
  get 'static_pages/draw_tree_submit'
  get 'static_pages/manage_over_hit'
  post 'static_pages/draw_tree_render'
  get 'static_pages/draw_tree_render' => 'static_pages/draw_tree_submit'
  # routes for elders 
  get 'static_pages/vincenzo_tomassi'
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/post.rb
class Post < ApplicationRecord
	has_rich_text :body
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, except: [:show]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
	@posts = @posts.sort_by{|obj| -obj.views}
  end

  # GET /posts/1 or /posts/1.json
  def show
  
	@post.views = @post.views + 1
	@post.save
	
	#gestione menu laterale 
	
	    @posts = Post.all
		@families = Array.new
		@posts.each do |post_s|
		
			#print(post_s.family_name.to_s+"\n")
			if (post_s.family==true)
				if not @families.include?(post_s.family_name.to_s)
					@families.push(post_s.family_name.to_s)
				end
			end
			
		end
		
		#print(@families)
		#####################################################
		@couples = Hash.new
		
		@families = @families.sort
		
		@families.each do |family_soprannome|
			buff_post = Array.new
				@posts.each do |post|
					if (family_soprannome==post.family_name.to_s and post.family==true)
						buff_post.push(post)
					end
				end
			
			@families = @families
			buff_post = buff_post.sort_by{|obj| obj.id}
			
			#gestione albero come primo elemento del dropdown menu
			family_tree = buff_post.find {|e| e.title == "Albero Genealogico"}
			print("TEST FAMILY TREEE ===> "+family_tree.to_s)
			buff_post.delete(family_tree)
			
			print("################buffpost###################")
			print(buff_post)
			if not(family_tree==nil)
				buff_post.unshift(family_tree)
			end
			print("################buffpost###################")
			
		@couples[family_soprannome] = buff_post
		print(@couples)
		
		end
	
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
	print(@post.body.to_s)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :views, :family, :family_name, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
	<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :family? %>
     <%= form.check_box :family %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :family_name %>
    <%= form.text_field :family_name %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>
  <hr>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  

app/views/posts/_menu.html.erb
 
            <div class="bg-light border rounded-3 p-1 h-100">
                <ul class="nav flex-sm-column flex-row mb-auto justify-content-center" aria-expanded="false">
					
					
					
					<% @posts.each do |post| %>	
					<li>
						<% if (post.family==false) %> 	
										<button type="button" class="btn bg-transparent">
										<li><%= link_to "#{post.title.to_s}", post_path(:id => post.id.to_i) %></li>
										</button>	
						<% end %>
					</li>
					<% end %>
					
					
					
					<!-- <li>
					  <button type="button" class="btn bg-transparent dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
						Chiss Mirena
					  </button>
					  <ul class="dropdown-menu">
						<li><a class="dropdown-item">Albero Genealogico</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item"><%= link_to "QR Vincenzo Tomassi", static_pages_vincenzo_tomassi_path %></a></li>
					  </ul>
					  </br>
					</li> -->
					
					<li>
						<% @couples.each do |family_soprannome, post_array| %>
							<button type="button" class="btn bg-transparent dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
								<%= family_soprannome %>
							</button>
						
								<ul class="dropdown-menu">
							
								<% post_array.each do |post| %>
									
									
										<li><%= link_to "#{post.title.to_s}", post_path(:id => post.id.to_i), {:class => "dropdown-item"} %></li>
									
									 
								<% end %>
								</ul>
								</br>
						<% end %>
					 
					</li>
					
                </ul>
            </div>
       

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row text-center">
	<h1>Pannello di controllo </h1>
</div>

<div class="table-responsive">
    <table class="table table-striped table-hover mx-auto w-auto">
		  <thead>
			<tr>
			  <th>Title</th>
			  <th>Views</th>
			  <th>Operations</th>
			  <th colspan="3"></th>
			</tr>
		  </thead>


		  <tbody>
			<% @posts.each do |post| %>
			  <tr>
				<td><%= post.title %></td>
				<td><%= post.views %></td>
				<td><%= link_to 'Show', post %> <%= link_to 'Edit', edit_post_path(post) %> <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<td></td>
				<td></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>
	</div>
	

<br>

<div class="row text-center" >
	<div class="col">
	<button type="button" class="btn btn-dark" id="post_button">
		<%= link_to 'NEW POST', new_post_path %>
	</button>
	</div>
</div>

app/views/posts/new.html.erb
<div class="row"></div>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 text-center border-dark border-bottom" >
  <h1>New Post</h1>
	<p>
	<%= render 'form', post: @post %>
	</p>
	<%= link_to 'Back', posts_path %>
  </div>
  <div class="col-sm-3"></div>
</div>
<div class="row"></div>

app/views/posts/show.html.erb
<%= stylesheet_pack_tag 'projects', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'hello', 'data-turbolinks-track': 'reload' %>

<header class="py-3 mb-4 border-bottom shadow">
    <div class="container-fluid align-items-center d-flex ">
       
    </div>
</header>

<div class="container-fluid ">
    <div class="row">
	 
	 <div class="col-sm-3 ">
	 <%=render 'menu' %> 
	  </div>
	  
     <main class="col-sm-9 ">
            <div class="bg-light border rounded-3 p-3">
			
                <h2>  <%= @post.title %> </h2>
				
                <hr />
				
				<h2> Pubblicato il: <%= @post.created_at %> </h2>
				
                <hr />
				
				<p>
				 <%= @post.body %>
				</p>
			</div>
        </main>
    </div>
</div>



<!--
DA METTERE LA CONDIZIONE SE IL CONTENT WRITER è LOGGATO
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
-->