config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :admin do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_admin_registration" # custom path to sign_up/registration
  end
  
  devise_for :admins, :skip => [:registrations]
	  
  resources :posts
  root to: "static_pages#home"
  #root to: "posts#index"
  get 'static_pages/contacts'
  get 'static_pages/projects'
  get 'static_pages/shop'
  get 'static_pages/draw_tree_submit'
  get 'static_pages/manage_over_hit'
  post 'static_pages/draw_tree_render'
  get 'static_pages/draw_tree_render' => 'static_pages/draw_tree_submit'
  # routes for elders 
  get 'static_pages/vincenzo_tomassi'
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('android-icon-36x36.png') %>
    <title> <%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<%= include_gon %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
	
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
      <script type="text/javascript">google.load('visualization', '1.0', {'packages':['corechart']});</script> 
	   <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=MedievalSharp" />
  </head>
  <body>
    <header>
		<!--navbar-->
	
		
		<div class="row">
			<nav class="navbar navbar-light container-fluid navbar-expand-lg bg-light border-dark border-bottom border-top">
				<div class="col">
				
					<a href="/" class="navbar-brand d-flex w-50 mr-auto"><img
							 src="https://i.ibb.co/TwqRpy1/Whats-App-Image-2021-08-08-at-16-59-54.jpg"
							 height="50"
							 alt=""
							 loading="lazy"
							 /></a>
				
				</div>
				<div class="col">
				
					<ul class="navbar-nav w-100 justify-content-center text-center">
					  <li class="nav-item active">
						<%= link_to "Home", root_path %> 
					  </li>
					  <li class="nav-item">
					   <%= link_to "Shop", static_pages_shop_path %>
					  </li>
					  <li class="nav-item">
						<%= link_to "Contatti", static_pages_contacts_path %>
					  </li>
						 <li class="nav-item">
						<%= link_to "Attività", static_pages_projects_path %>
					  </li>
					  <% if admin_signed_in? %>
						<li class="nav-item"><%= link_to "Create Post", posts_path %></li>
						<li class="nav-item"><%= link_to "Automate Draw Tree (alfa)", static_pages_draw_tree_submit_path %></li>
						<li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
					<% end %>
				</ul>
				
				</div>
				<div class="col">
				
					<ul class="nav navbar-nav ml-auto w-100 justify-content-end text-center">
					<li class="nav-item"><a class="nav-link" href="https://m.facebook.com/chissdaquin/"><i class="fab fa-facebook-f"></i></a></li>
					<li class="nav-item"><a class="nav-link" href="https://www.instagram.com/chissdaquin/"><i class="fab fa-instagram"></i></a></li>
				
				</ul>	
				
				</div>
					</nav>
			</div>
		
		
			
		
			
				
	
		<!-- Navbar -->
	</header>
  <%= yield %>
<!--Main Navigation-->
  </body>
</html>